spring:
  application:
    name: EurekaServer
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #      defaultZone: http://localhost:9000/eureka/, http://localhost:9001/eureka/, http://library:9002/eureka
      defaultZone:  http://localhost:9001/eureka/, http://localhost:9002/eureka/
server:
  port: 9000
