# CI for Android application
name: Android CI/CD

on:
  push:
    branches: [
      "main", "dev",
      "feat/**", "refactor/**",
      "style/**", "fix/**"
    ]
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: '21'

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk